// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdvEnLS4nbQXpSjyeVU1sPKqgqQpX_PA',
    appId: '1:1003319069889:web:d7a64807b983a945309840',
    messagingSenderId: '1003319069889',
    projectId: 'rjmm-f7750',
    authDomain: 'rjmm-f7750.firebaseapp.com',
    storageBucket: 'rjmm-f7750.appspot.com',
    measurementId: 'G-E2EM684GCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpx2Qrkqkm_kVRy_LuWjW62MypHSxTx2E',
    appId: '1:1003319069889:android:117c1d099ab487db309840',
    messagingSenderId: '1003319069889',
    projectId: 'rjmm-f7750',
    storageBucket: 'rjmm-f7750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeAgeKQMrNe0Fi5FLEqt9J32w2A0rjUQk',
    appId: '1:1003319069889:ios:2cad2942c24561fa309840',
    messagingSenderId: '1003319069889',
    projectId: 'rjmm-f7750',
    storageBucket: 'rjmm-f7750.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeAgeKQMrNe0Fi5FLEqt9J32w2A0rjUQk',
    appId: '1:1003319069889:ios:2cad2942c24561fa309840',
    messagingSenderId: '1003319069889',
    projectId: 'rjmm-f7750',
    storageBucket: 'rjmm-f7750.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );
}
